version: "3.9"

services:
  db:
    image: postgres:16
    container_name: wallet_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wallet_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: wallet_service_app
    restart: always

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:admin@db:5432/wallet_service_db

    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: